base_prj/base_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/', include('sns.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_prj/sns/urls.py
from django.urls import path
from . import views



app_name = 'sns'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('new/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/edit/', views.edit_posting, name='edit_posting'),
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),
    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'),
]

base_prj/sns/models.py
from django.db import models
from datetime import datetime


class Posting(models.Model):
    content = models.CharField(max_length=500)
    icon = models.CharField(max_length=20, default='fas fa-question')
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:10]}'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content}'

base_prj/sns/views.py
from django.shortcuts import render, redirect,get_object_or_404,get_list_or_404
from .models import Posting, Comment

# Create your views here.


def posting_list(request):
    postings = Posting.objects.all()
    return render(request, 'sns/list.html', {
        'postings': postings,
    })


def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all()
    return render(request,'sns/detail.html', {
        'posting': posting,
        'comments': comments,
    })


def create_posting(request):
    if request.method == 'POST':
        posting = Posting()
        posting.content = request.POST.get('content')
        posting.icon = request.POST.get('icon')
        posting.image = request.FILES.get('image')
        posting.save()
        return redirect('sns:posting_detail', posting.id)
    else:
        return redirect('sns:posting_list')


def edit_posting(request):
    pass


def delete_posting(request):
    pass


def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method == "POST":
        comment = Comment()
        comment.content = request.POST.get('comment')
        comment.posting = posting
        comment.save()
        return redirect('sns:posting_detail', posting.id)
    else:
        return redirect('sns:posting_detail', posting.id)

base_prj/sns/templates/sns/_header.html
<header class="mt-3">
    <form action="{% url 'sns:create_posting' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- icon select tag -->

        <div class="form-row align-items-center">
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="fas fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                </select>
            </div>
            <!-- content input tag tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" placeholder="Feels like...">
            </div>

            <!-- file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    <input id="image" class="custom-file-input" name="image" type="file" accept="image/*">
                    <label for="image" class="custom-file-label">Choose image</label>
                </div>
            </div>


            <!--submit button-->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</header>

base_prj/sns/templates/sns/_nav.html
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'sns:posting_list' %}" class="nav-link {% block list %}{% endblock %}">SNS</a>
    </li>

    <li class="nav-item">
        <a  class="nav-link {% block detail %}{% endblock %}" aria-disabled="true">Detail</a>
    </li>
</ul>

base_prj/sns/templates/sns/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>My SNS</title>
</head>
<body>
{% include 'sns/_nav.html' %}

<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</html>

base_prj/sns/templates/sns/detail.html
{% extends 'sns/base.html' %}
{% block detail %}active{% endblock %}
{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img class="card-img-top image-fluid" src="{{ posting.image.url }}" alt="{{ posting.image }}">
                {% else %}
                    <img src="http://lorempixel.com/g/300/400" class="card-image-top" alt="random_image">
                {% endif %}
                <div class="card-body">
                    <i class="{{ posting.icon }}"></i>
                    <hr>
                    <p class="card-text">{{ posting.content }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <form action="/sns/{{ posting.id }}/comments/create/" method="POST">
                        {% csrf_token %}
                        <label for="comment">leave comment</label>
                        <input type="text" name="comment" id="comment" class="form-control">
                    </form>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-6">
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% if comments %}
                        {% for comment in comments %}
                            <li class="list-group-item mb-1">{{ comment.content }}</li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item mb-1">No comments yet.. </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}

base_prj/sns/templates/sns/list.html
{% extends 'sns/base.html' %}
{% block list %}active{% endblock %}
{% block body %}
    {% include 'sns/_header.html' %}
    <hr>
    {% if postings %}
        <section class="card-columns">
            {% for posting in postings %}
                <article class="card mb-2">
                    {% if posting.image %}
                        <a href="{% url 'sns:posting_detail' posting.id %}">
                            <img class="card-img-top image-fluid" src="{{ posting.image.url }}"
                                 alt="{{ posting.image }}">
                        </a>
                    {% else %}
                        <a href="{% url 'sns:posting_detail' posting.id %}">
                            <img src="http://lorempixel.com/g/150/75" class="card-img-top"
                                 alt="random_image_{{ forloop.counter }}">
                        </a>
                    {% endif %}

                    <div class="card-body">
                        {% for i in posting.comment_set.all %}
                            <i class="{{ posting.icon }} fa-2x"></i>
                        {% endfor %}
                    </div>
                </article>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}